### ISSUE TITLE
Userregistrierung

### ISSUE THREAD

**Issue by zarat** [zarat/SimpleMail#1]
Derzeit muss man Accounts noch manuell in der Datei users.xml eintragen. Dazu soll noch eine schöne grafische Funktion kommen. Derzeit wird ein Benutzer neu angelegt sobald er sich über POP anmeldet. Soll aber wegkommen.

**Comment by mbrain** [comment]
Vielleicht das ganze in eine INI Datei auslagern damit man es einfacher bearbeiten kann :D

**Comment by zarat** [comment]
Stimmt ist auch leichter mit Properties darauf zuzugreifen. Sobald die Passwörter verschlüsselt werden kann die aber ohnehin nicht mehr jeder einfach so bearbeiten.
